stages:
  - mirror

mirror_main_to_github:
  stage: mirror
  only:
    - main
  script:
    - git config --global user.name "Eitan Kay"
    - git config --global user.email "20345138+0x3k@users.noreply.github.com"
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git
    - git fetch --unshallow
    - git push -u github HEAD:main --force
  variables:
    GITHUB_REPO: 'unity-sdk'